services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  bot:
    build: .
    container_name: bot
    command: python bot/main.py
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - web
    restart: always